export enum Permission {
  /** User */
  GET_USERS = 'GET_USERS',
  GET_USER = 'GET_USER',
  GET_PROFILE = 'GET_PROFILE',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  /** Roles */
  GET_ROLES = 'GET_ROLES',
  GET_ASSIGNED_ROLES = 'GET_ASSIGNED_ROLES',

  /** Claims */
  GET_CLAIMS = 'GET_CLAIMS',
  GET_ASSIGNED_CLAIMS = 'GET_ASSIGNED_CLAIMS',
}
